# ETL Project: Leading causes of death in the United States

#### Aim:
An analysis on the leading causes of death in the United States. This case study seeks to analyze the top causes of deaths from 2013 to 2016 by ranking death causes by year, state, and age-adjusted death rates. Further, would U.S. chronic disease indicators provide any insight into risk factors that may be associated with those leading causes of death? 

#### Notes:
The 10 leading causes of death are classified by the International Classification of Diseases, Tenth Revision (ICD-10). Age-adjusted death rates are per 100,000 population. 


#### Data provided by:
* [CDC/HCHS](https://catalog.data.gov/dataset/age-adjusted-death-rates-for-the-top-10-leading-causes-of-death-united-states-2013)

* [CDC](https://catalog.data.gov/dataset/u-s-chronic-disease-indicators-cdi)

In [1]:
# import dependencies
import pandas as pd
import pymysql
from sqlalchemy import create_engine

In [2]:
# read csv file for data on leading causes of death
leading_causes_death_df = pd.read_csv('Resources/NCHS_-_Leading_Causes_of_Death__United_States.csv')

In [3]:
# preview the dataframe created
leading_causes_death_df.head()

,Year,113 Cause Name,Cause Name,State,Deaths,Age-adjusted Death Rate
0,2016,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional injuries,Alabama,2755,55.5
1,2016,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional injuries,Alaska,439,63.1
2,2016,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional injuries,Arizona,4010,54.2
3,2016,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional injuries,Arkansas,1604,51.8
4,2016,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional injuries,California,13213,32.0

In [4]:
## cleaning the database

# Remove cause_name and state columns, Rename columns into a new dataframe
leading_causes = leading_causes_death_df[['Year', '113 Cause Name', 'State','Deaths', 'Age-adjusted Death Rate']].copy()
leading_causes = leading_causes.rename(columns={
    "Year":"year",
    "113 Cause Name": "cause_name",
    "State": "state",
    "Deaths": "deaths",
    "Age-adjusted Death Rate": "age-ajusted_death_rate"
})
leading_causes.sort_values(by=["year"]).head()

,year,cause_name,state,deaths,age-ajusted_death_rate
10295,1999,"Accidents (unintentional injuries) (V01-X59,Y8...",Wyoming,258,52.8
1418,1999,Alzheimer's disease (G30),Minnesota,1083,21.1
8726,1999,"Intentional self-harm (suicide) (*U03,X60-X84,...",Illinois,1020,8.3
7016,1999,"Nephritis, nephrotic syndrome and nephrosis (N...",Michigan,1417,15.0
4334,1999,Diabetes mellitus (E10-E14),New Hampshire,294,25.3

In [5]:
# Filter leading_causes for years >=2013
leading_causes_2013_to_2016 = leading_causes.loc[leading_causes['year'] >= 2013,:]
leading_causes_2013_to_2016=leading_causes_2013_to_2016.sort_values(by=['year'])

#### PUT THIS DATAFRAME INTO THE DATABASE
leading_causes_2013_to_2016.head()

,year,cause_name,state,deaths,age-ajusted_death_rate
10281,2013,"Accidents (unintentional injuries) (V01-X59,Y8...",Wyoming,325,55.2
3708,2013,Chronic lower respiratory diseases (J40-J47),Virginia,3181,37.3
3726,2013,Chronic lower respiratory diseases (J40-J47),Washington,2933,39.4
8946,2013,"Intentional self-harm (suicide) (*U03,X60-X84,...",Montana,243,23.7
3744,2013,Chronic lower respiratory diseases (J40-J47),West Virginia,1590,64.6

In [6]:
# # Group dataframe by year and cause_name, finding the sum of deaths 
# leading_causes_2013_to_2016_grouped=leading_causes_2013_to_2016.groupby(["year", "cause_name"]).sum().copy()
# leading_causes_2013_to_2016_grouped.head()

## Connect to MySQL database

In [7]:
#engine = create_engine("mysql://root:Codingislife92!@localhost:3306/leading_causes_of_death_db")
pymysql.install_as_MySQLdb()
connection_string = "root:bdasl2019@127.0.0.1/leading_causes_of_death_db"
engine = create_engine(f'mysql://{connection_string}')

In [8]:
leading_causes_2013_to_2016.to_sql(name='leading_causes', con=engine, if_exists='append', index=False)

In [9]:
pd.read_sql_query('SELECT * FROM leading_causes', con=engine).head()

,year,cause_name,state,deaths,age-ajusted_death_rate
0,2013,"Accidents (unintentional injuries) (V01-X59,Y8...",Wyoming,325,55.2
1,2013,Chronic lower respiratory diseases (J40-J47),Virginia,3181,37.3
2,2013,Chronic lower respiratory diseases (J40-J47),Washington,2933,39.4
3,2013,"Intentional self-harm (suicide) (*U03,X60-X84,...",Montana,243,23.7
4,2013,Chronic lower respiratory diseases (J40-J47),West Virginia,1590,64.6

In [10]:
engine.table_names()

['leading_causes']

In [11]:
# QUERY TO SUM DEATHS, GROUPED BY YEAR AND CAUSE OF DEATH

pd.read_sql_query('SELECT year, cause_name,\
                  SUM(deaths) as total_US_deaths\
                  FROM leading_causes\
                  GROUP BY year, cause_name\
                  HAVING year >= 2013\
                  ORDER BY year ASC', con=engine)

    year                                         cause_name  total_US_deaths
0   2013  Accidents (unintentional injuries) (V01-X59,Y8...        1305570.0
1   2013                                         All Causes       25969930.0
2   2013                          Alzheimer's disease (G30)         847670.0
3   2013                 Cerebrovascular diseases (I60-I69)        1289780.0
4   2013       Chronic lower respiratory diseases (J40-J47)        1492050.0
5   2013                        Diabetes mellitus (E10-E14)         755780.0
6   2013        Diseases of heart (I00-I09,I11,I13,I20-I51)        6111050.0
7   2013                  Influenza and pneumonia (J09-J18)         569790.0
8   2013  Intentional self-harm (suicide) (*U03,X60-X84,...         411490.0
9   2013                      Malignant neoplasms (C00-C97)        5848810.0
10  2013  Nephritis, nephrotic syndrome and nephrosis (N...         471120.0
11  2014  Accidents (unintentional injuries) (V01-X59,Y8...        1359280.0
12  2014                                         All Causes       26264180.0
13  2014                          Alzheimer's disease (G30)         935410.0
14  2014                 Cerebrovascular diseases (I60-I69)        1331030.0
15  2014       Chronic lower respiratory diseases (J40-J47)        1471010.0
16  2014                        Diabetes mellitus (E10-E14)         764880.0
17  2014        Diseases of heart (I00-I09,I11,I13,I20-I51)        6143480.0
18  2014                  Influenza and pneumonia (J09-J18)         552270.0
19  2014  Intentional self-harm (suicide) (*U03,X60-X84,...         428260.0
20  2014                      Malignant neoplasms (C00-C97)        5917000.0
21  2014  Nephritis, nephrotic syndrome and nephrosis (N...         481460.0
22  2015  Accidents (unintentional injuries) (V01-X59,Y8...        1465710.0
23  2015                                         All Causes       27126300.0
24  2015                          Alzheimer's disease (G30)        1105610.0
25  2015                 Cerebrovascular diseases (I60-I69)        1403230.0
26  2015       Chronic lower respiratory diseases (J40-J47)        1550410.0
27  2015                        Diabetes mellitus (E10-E14)         795350.0
28  2015        Diseases of heart (I00-I09,I11,I13,I20-I51)        6338420.0
29  2015                  Influenza and pneumonia (J09-J18)         570620.0
30  2015  Intentional self-harm (suicide) (*U03,X60-X84,...         441930.0
31  2015                      Malignant neoplasms (C00-C97)        5959300.0
32  2015  Nephritis, nephrotic syndrome and nephrosis (N...         499590.0
33  2016  Accidents (unintentional injuries) (V01-X59,Y8...        1613740.0
34  2016                                         All Causes       25318615.0
35  2016                          Alzheimer's disease (G30)        1161030.0
36  2016                 Cerebrovascular diseases (I60-I69)        1421420.0
37  2016       Chronic lower respiratory diseases (J40-J47)        1545960.0
38  2016                        Diabetes mellitus (E10-E14)         800580.0
39  2016        Diseases of heart (I00-I09,I11,I13,I20-I51)        6352600.0
40  2016                  Influenza and pneumonia (J09-J18)         515370.0
41  2016  Intentional self-harm (suicide) (*U03,X60-X84,...         449650.0
42  2016                      Malignant neoplasms (C00-C97)        5980380.0
43  2016  Nephritis, nephrotic syndrome and nephrosis (N...         500460.0

## NCHS Leading Causes of Death by State

In [23]:
# Deaths per state
state_deaths = pd.read_sql_query('SELECT state, deaths as total_state_deaths \
                FROM leading_causes', con=engine)
deaths_state = state_deaths.groupby(['state'])
deaths_state_df = deaths_state['total_state_deaths'].sum()
deaths_state_df.sort_values(ascending=False)

state
United States           90756855
California               8986635
Florida                  6602975
Texas                    6417540
New York                 5337340
Pennsylvania             4530500
Ohio                     4050965
Illinois                 3675160
Michigan                 3324315
North Carolina           3008225
Georgia                  2703585
New Jersey               2488580
Tennessee                2297305
Virginia                 2221955
Indiana                  2147075
Missouri                 2075190
Massachusetts            1904690
Arizona                  1854480
Washington               1852165
Alabama                  1776320
Wisconsin                1767615
Maryland                 1602360
South Carolina           1601570
Kentucky                 1598475
Louisiana                1529915
Minnesota                1431975
Oklahoma                 1377770
Colorado                 1232825
Oregon                   1193275
Mississippi              1099250
Arkansas                 1096555
Connecticut              1030335
Iowa                     1023660
Kansas                    893715
Nevada                    799060
West Virginia             776500
New Mexico                604330
Utah                      582330
Nebraska                  552580
Maine                     480965
Idaho                     444975
New Hampshire             403225
Hawaii                    375960
Rhode Island              341025
Montana                   333665
Delaware                  293450
South Dakota              266455
North Dakota              216185
Vermont                   201345
District of Columbia      166270
Wyoming                   162355
Alaska                    145750
Name: total_state_deaths, dtype: int64

In [24]:
# Deaths in each state per cause per year
state_deaths = pd.read_sql_query('SELECT state, cause_name, year, deaths as total_state_deaths \
                FROM leading_causes', con=engine)
deaths_state = state_deaths.groupby(['state', 'cause_name', 'year'])
deaths_state_df = deaths_state['total_state_deaths'].sum()
print(deaths_state_df.sort_values)

<bound method Series.sort_values of state    cause_name                                                             year
Alabama  Accidents (unintentional injuries) (V01-X59,Y85-Y86)                   2013     11645
                                                                                2014     12315
                                                                                2015     12760
                                                                                2016     13775
         All Causes                                                             2013    250945
                                                                                2014    251075
                                                                                2015    259545
                                                                                2016    262330
         Alzheimer's disease (G30)                                              2013      6990
                                                                                2014      9425
                                                                                2015     11410
                                                                                2016     12535
         Cerebrovascular diseases (I60-I69)                                     2013     13020
                                                                                2014     13315
                                                                                2015     14685
                                                                                2016     14835
         Chronic lower respiratory diseases (J40-J47)                           2013     15215
                                                                                2014     15250
                                                                                2015     16395
                                                                                2016     16630
         Diabetes mellitus (E10-E14)                                            2013      6745
                                                                                2014      6405
                                                                                2015      6275
                                                                                2016      5915
         Diseases of heart (I00-I09,I11,I13,I20-I51)                            2013     62360
                                                                                2014     62305
                                                                                2015     64905
                                                                                2016     64160
         Influenza and pneumonia (J09-J18)                                      2013      5175
                                                                                2014      5155
                                                                                         ...
Wyoming  Cerebrovascular diseases (I60-I69)                                     2015       990
                                                                                2016      1040
         Chronic lower respiratory diseases (J40-J47)                           2013      1935
                                                                                2014      1715
                                                                                2015      1840
                                                                                2016      1635
         Diabetes mellitus (E10-E14)                                            2013       445
                                                                                2014       550
                                                                                2015       680
                                                                                2016       560
         Diseases of heart (I00-I09,I11,I13,I20-I51)                            2013      4695
                                                                                2014      5175
                                                                                2015      5150
                                                                                2016      5255
         Influenza and pneumonia (J09-J18)                                      2013       560
                                                                                2014       565
                                                                                2015       495
                                                                                2016       495
         Intentional self-harm (suicide) (*U03,X60-X84,Y87.0)                   2013       645
                                                                                2014       600
                                                                                2015       785
                                                                                2016       720
         Malignant neoplasms (C00-C97)                                          2013      4730
                                                                                2014      4610
                                                                                2015      4655
                                                                                2016      4810
         Nephritis, nephrotic syndrome and nephrosis (N00-N07,N17-N19,N25-N27)  2013       280
                                                                                2014       390
                                                                                2015       430
                                                                                2016       330
Name: total_state_deaths, Length: 2288, dtype: int64>

In [25]:
# Deaths per cause
state_causes = pd.read_sql_query('SELECT cause_name, deaths as total_state_deaths \
                FROM leading_causes', con=engine)
state_causes_group = state_causes.groupby(['cause_name'])
state_causes_df = state_causes_group['total_state_deaths'].sum()
state_causes_df.sort_values(ascending=False)

cause_name
All Causes                                                               104679025
Diseases of heart (I00-I09,I11,I13,I20-I51)                               24945550
Malignant neoplasms (C00-C97)                                             23705490
Chronic lower respiratory diseases (J40-J47)                               6059430
Accidents (unintentional injuries) (V01-X59,Y85-Y86)                       5744300
Cerebrovascular diseases (I60-I69)                                         5445460
Alzheimer's disease (G30)                                                  4049720
Diabetes mellitus (E10-E14)                                                3116590
Influenza and pneumonia (J09-J18)                                          2208050
Nephritis, nephrotic syndrome and nephrosis (N00-N07,N17-N19,N25-N27)      1952630
Intentional self-harm (suicide) (*U03,X60-X84,Y87.0)                       1731330
Name: total_state_deaths, dtype: int64

# Chronic Disease Indicators

#### Column Descriptions:
* YearStart - Starting Year
* YearEnd - Ending Year
* LocationAbbr - Location Abbreviation
* LocationDesc - Location Description
* DataSource - Data Source Abbreviation
* Topic - Topic
* Question - Question full-length text
* Response - Response
* DataValueUnit - The unit, such as $, %, years, etc.
* DataValueType - The data type, such as prevalence or mean
* DataValue - Data Value, such as 14.7 or Category 1
* DataValueAlt - Equal to Data Value, but formatting is numeric
* DataValueFootnoteSymbol	- Footnote Symbol
* DatavalueFootnote - Footnote Text
* LowConfidenceLimit - Low Confidence Limit
* HighConfidenceLimit - High Confidence Limit
* StratificationCategory1	- The category of the stratification, such as * Gender, Overall, or Race/Ethnicity
* Stratification1	- The stratification within the category, such as Male or Female, White/non-Hispanic, Hispanic, Black/non-Hispanic, American Indian or Alaska Native, Asian or Pacific Islander, Multi-racial/non-Hispanic, Other/non-Hispanic, or Overall
* StratificationCategory2
* Stratification2	
* StratificationCategory3
* Stratification3	
* GeoLocation	- Location code to be used for Geocoding
* ResponseID - Identifier for the Response
* LocationID - Location Identifier
* TopicID	
* QuestionID - Question Identifier
* DataValueTypeID	- Identifier for the Data Value Type
* StratificationCategoryID1 - Identifier for stratification category 1
* StratificationID1 - Identifier for stratification 1
* StratificationCategoryID2	
* StratificationID2	
* StratificationCategoryID3	
* StratificationID3

In [13]:
# read chronic diseases indicators csv
CDI_df = pd.read_csv('Resources/U.S._Chronic_Disease_Indicators__CDI_.csv')
CDI_df.head()

/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (7,10,18,19,20,21,23,30,31,32,33) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,YearStart,YearEnd,LocationAbbr,LocationDesc,DataSource,Topic,Question,Response,DataValueUnit,DataValueType,...,LocationID,TopicID,QuestionID,DataValueTypeID,StratificationCategoryID1,StratificationID1,StratificationCategoryID2,StratificationID2,StratificationCategoryID3,StratificationID3
0,2016,2016,US,United States,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,59,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
1,2016,2016,AL,Alabama,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,1,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
2,2016,2016,AK,Alaska,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,2,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
3,2016,2016,AZ,Arizona,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,4,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
4,2016,2016,AR,Arkansas,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,5,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN

In [14]:
## CLEAN UP DATAFRAME
# Remove uncessary columns
CDI_df = CDI_df[['YearStart', 'LocationAbbr', 'LocationDesc', 'Topic', 'Question', 'DataValue', 'DataValueUnit', 'DataValueType', 'StratificationCategory1', 'Stratification1']]

CDI_df.head()

,YearStart,LocationAbbr,LocationDesc,Topic,Question,DataValue,DataValueUnit,DataValueType,StratificationCategory1,Stratification1
0,2016,US,United States,Alcohol,Binge drinking prevalence among adults aged >=...,16.9,%,Crude Prevalence,Overall,Overall
1,2016,AL,Alabama,Alcohol,Binge drinking prevalence among adults aged >=...,13,%,Crude Prevalence,Overall,Overall
2,2016,AK,Alaska,Alcohol,Binge drinking prevalence among adults aged >=...,18.2,%,Crude Prevalence,Overall,Overall
3,2016,AZ,Arizona,Alcohol,Binge drinking prevalence among adults aged >=...,15.6,%,Crude Prevalence,Overall,Overall
4,2016,AR,Arkansas,Alcohol,Binge drinking prevalence among adults aged >=...,15,%,Crude Prevalence,Overall,Overall

In [22]:
CDI_topic_df = CDI_df[['Topic']]
CDI_topic_df

                         Topic
0                      Alcohol
1                      Alcohol
2                      Alcohol
3                      Alcohol
4                      Alcohol
5                      Alcohol
6                      Alcohol
7                      Alcohol
8                      Alcohol
9                      Alcohol
10                     Alcohol
11                     Alcohol
12                     Alcohol
13                     Alcohol
14                     Alcohol
15                     Alcohol
16                     Alcohol
17                     Alcohol
18                     Alcohol
19                     Alcohol
20                     Alcohol
21                     Alcohol
22                     Alcohol
23                     Alcohol
24                     Alcohol
25                     Alcohol
26                     Alcohol
27                     Alcohol
28                     Alcohol
29                     Alcohol
...                        ...
519688             Oral Health
519689             Oral Health
519690             Oral Health
519691             Oral Health
519692             Oral Health
519693             Oral Health
519694             Oral Health
519695             Oral Health
519696             Oral Health
519697             Oral Health
519698             Oral Health
519699  Overarching Conditions
519700  Overarching Conditions
519701  Overarching Conditions
519702  Overarching Conditions
519703  Overarching Conditions
519704  Overarching Conditions
519705  Overarching Conditions
519706  Overarching Conditions
519707  Overarching Conditions
519708  Overarching Conditions
519709                 Tobacco
519710                 Tobacco
519711                 Tobacco
519712                 Tobacco
519713                 Tobacco
519714                 Tobacco
519715                 Tobacco
519716                 Tobacco
519717              Disability

[519718 rows x 1 columns]

In [16]:
# Obtain rows only for the all of the United States
CDI_US = CDI_df.loc[CDI_df['LocationAbbr']=="US",:]

# Obtain rows only for the years >=2013
CDI_US = CDI_US.loc[CDI_US['YearStart']>=2013, :]
CDI_US

,YearStart,LocationAbbr,LocationDesc,Topic,Question,DataValue,DataValueUnit,DataValueType,StratificationCategory1,Stratification1
0,2016,US,United States,Alcohol,Binge drinking prevalence among adults aged >=...,16.9,%,Crude Prevalence,Overall,Overall
55,2016,US,United States,Alcohol,Binge drinking prevalence among adults aged >=...,17.9,%,Age-adjusted Prevalence,Overall,Overall
110,2016,US,United States,Alcohol,Binge drinking prevalence among adults aged >=...,21.9,%,Crude Prevalence,Gender,Male
165,2016,US,United States,Alcohol,Binge drinking prevalence among adults aged >=...,22.5,%,Age-adjusted Prevalence,Gender,Male
220,2016,US,United States,Alcohol,Binge drinking prevalence among adults aged >=...,12,%,Crude Prevalence,Gender,Female
275,2016,US,United States,Alcohol,Binge drinking prevalence among adults aged >=...,13.1,%,Age-adjusted Prevalence,Gender,Female
874,2016,US,United States,Alcohol,Binge drinking prevalence among women aged 18-...,18.7,%,Crude Prevalence,Overall,Overall
1201,2016,US,United States,Alcohol,Binge drinking frequency among adults aged >= ...,4.6,Number,Mean,Overall,Overall
1254,2016,US,United States,Alcohol,Binge drinking frequency among adults aged >= ...,4.7,Number,Age-adjusted Mean,Overall,Overall
1310,2016,US,United States,Alcohol,Binge drinking frequency among adults aged >= ...,5,Number,Mean,Gender,Male
1365,2016,US,United States,Alcohol,Binge drinking frequency among adults aged >= ...,5,Number,Age-adjusted Mean,Gender,Male
1420,2016,US,United States,Alcohol,Binge drinking frequency among adults aged >= ...,3.5,Number,Mean,Gender,Female
1475,2016,US,United States,Alcohol,Binge drinking frequency among adults aged >= ...,3.6,Number,Age-adjusted Mean,Gender,Female
1935,2016,US,United States,Alcohol,Binge drinking intensity among adults aged >= ...,7.4,Number,Mean,Overall,Overall
2125,2016,US,United States,Alcohol,Binge drinking intensity among adults aged >= ...,7.1,Number,Age-adjusted Mean,Overall,Overall
2180,2016,US,United States,Alcohol,Binge drinking intensity among adults aged >= ...,8.5,Number,Mean,Gender,Male
2235,2016,US,United States,Alcohol,Binge drinking intensity among adults aged >= ...,8.2,Number,Age-adjusted Mean,Gender,Male
2290,2016,US,United States,Alcohol,Binge drinking intensity among adults aged >= ...,5.6,Number,Mean,Gender,Female
2345,2016,US,United States,Alcohol,Binge drinking intensity among adults aged >= ...,5.3,Number,Age-adjusted Mean,Gender,Female
2943,2016,US,United States,Alcohol,Heavy drinking among adults aged >= 18 years,6.5,%,Crude Prevalence,Overall,Overall
2990,2016,US,United States,Alcohol,Heavy drinking among adults aged >= 18 years,6.7,%,Age-adjusted Prevalence,Overall,Overall
3045,2016,US,United States,Alcohol,Heavy drinking among adults aged >= 18 years,7.1,%,Crude Prevalence,Gender,Male
3100,2016,US,United States,Alcohol,Heavy drinking among adults aged >= 18 years,7.2,%,Age-adjusted Prevalence,Gender,Male
3155,2016,US,United States,Alcohol,Heavy drinking among adults aged >= 18 years,5.9,%,Crude Prevalence,Gender,Female
3210,2016,US,United States,Alcohol,Heavy drinking among adults aged >= 18 years,6,%,Age-adjusted Prevalence,Gender,Female
3806,2016,US,United States,Alcohol,Heavy drinking among women aged 18-44 years,6.6,%,Crude Prevalence,Overall,Overall
4134,2016,US,United States,Arthritis,Arthritis among adults aged >= 18 years,25.8,%,Crude Prevalence,Overall,Overall
4185,2016,US,United States,Arthritis,Arthritis among adults aged >= 18 years,23.9,%,Age-adjusted Prevalence,Overall,Overall
4240,2016,US,United States,Arthritis,Arthritis among adults aged >= 18 years,22.1,%,Crude Prevalence,Gender,Male
4295,2016,US,United States,Arthritis,Arthritis among adults aged >= 18 years,20.9,%,Age-adjusted Prevalence,Gender,Male
...,...,...,...,...,...,...,...,...,...,...
519020,2013,US,United States,Cardiovascular Disease,Hospitalization for acute myocardial infarction,NaN,"cases per 10,000",Crude Rate,Overall,Overall
519021,2013,US,United States,Cardiovascular Disease,Hospitalization for acute myocardial infarction,NaN,"cases per 10,000",Age-adjusted Rate,Overall,Overall
519025,2014,US,United States,Diabetes,Adults with diagnosed diabetes aged >= 18 year...,NaN,%,Age-adjusted Prevalence,Overall,Overall
519026,2014,US,United States,Diabetes,Adults with diagnosed diabetes aged >= 18 year...,NaN,%,Crude Prevalence,Overall,Overall
519027,2016,US,United States,Diabetes,Adults with diagnosed diabetes aged >= 18 year...,NaN,%,Age-adjusted Prevalence,Overall,Overall
519028,2016,US,United States,Diabetes,Adults with diagnosed diabetes aged >= 18 year...,NaN,%,Crude Prevalence,Overall,Overall
519046,2014,US,United States,Diabetes,Amputation of a lower extremity attributable t...,NaN,NaN,Number,Overall,Overall
519047,2014,US,United States,Diabetes,Amputation of a lower extremity attributable t...,NaN,"cases per 10,000",Crude Rate,Overall,Overall
519048,2014,US,United States,Diabetes,Amputation of a lower extremity attributable t...,NaN,"cases per 10,000",Age-adjusted Rate,Overall,Overall
519049,2013,US,United States,Diabetes,Amputation of a lower extremity attributable t...,NaN,NaN,Number,Overall,Overall
519050,2013,US,United States,Diabetes,Amputation of a lower extremity attributable t...,NaN,"cases per 10,000",Crude Rate,Overall,Overall
519051,2013,US,United States,Diabetes,Amputation of a lower extremity attributable t...,NaN,"cases per 10,000",Age-adjusted Rate,Overall,Overall
519055,2014,US,United States,Diabetes,Foot examination among adults aged >= 18 years...,NaN,%,Age-adjusted Prevalence,Overall,Overall
519056,2014,US,United States,Diabetes,Foot examination among adults aged >= 18 years...,NaN,%,Crude Prevalence,Overall,Overall
519057,2016,US,United States,Diabetes,Foot examination among adults aged >= 18 years...,NaN,%,Age-adjusted Prevalence,Overall,Overall
519058,2016,US,United States,Diabetes,Foot examination among adults aged >= 18 years...,NaN,%,Crude Prevalence,Overall,Overall
519059,2016,US,United States,Diabetes,Glycosylated hemoglobin measurement among adul...,NaN,%,Crude Prevalence,Overall,Overall
519060,2016,US,United States,Diabetes,Glycosylated hemoglobin measurement among adul...,NaN,%,Age-adjusted Prevalence,Overall,Overall
519061,2014,US,United States,Diabetes,Glycosylated hemoglobin measurement among adul...,NaN,%,Crude Prevalence,Overall,Overall
519062,2014,US,United States,Diabetes,Glycosylated hemoglobin measurement among adul...,NaN,%,Age-adjusted Prevalence,Overall,Overall
519063,2014,US,United States,Diabetes,Dilated eye examination among adults aged >= 1...,NaN,%,Age-adjusted Prevalence,Overall,Overall
519064,2014,US,United States,Diabetes,Dilated eye examination among adults aged >= 1...,NaN,%,Crude Prevalence,Overall,Overall
519065,2016,US,United States,Diabetes,Dilated eye examination among adults aged >= 1...,NaN,%,Age-adjusted Prevalence,Overall,Overall
519066,2016,US,United States,Diabetes,Dilated eye examination among adults aged >= 1...,NaN,%,Crude Prevalence,Overall,Overall
519085,2014,US,United States,Diabetes,Hospitalization with diabetes as a listed diag...,NaN,NaN,Number,Overall,Overall
519086,2014,US,United States,Diabetes,Hospitalization with diabetes as a listed diag...,NaN,"cases per 10,000",Crude Rate,Overall,Overall
519087,2014,US,United States,Diabetes,Hospitalization with diabetes as a listed diag...,NaN,"cases per 10,000",Age-adjusted Rate,Overall,Overall
519088,2013,US,United States,Diabetes,Hospitalization with diabetes as a listed diag...,NaN,NaN,Number,Overall,Overall
519089,2013,US,United States,Diabetes,Hospitalization with diabetes as a listed diag...,NaN,"cases per 10,000",Crude Rate,Overall,Overall
519090,2013,US,United States,Diabetes,Hospitalization with diabetes as a listed diag...,NaN,"cases per 10,000",Age-adjusted Rate,Overall,Overall

In [17]:
# Separate crude prevalence and age-adjusted prevalence into separate dataframes
CDI_US_crude = CDI_US.loc[CDI_US['DataValueType']=="Crude Prevalence",:]
CDI_US_age_adjusted = CDI_US.loc[CDI_US['DataValueType']=="Age-adjusted Prevalence", :]

In [18]:
CDI_US_crude.head()

,YearStart,LocationAbbr,LocationDesc,Topic,Question,DataValue,DataValueUnit,DataValueType,StratificationCategory1,Stratification1
0,2016,US,United States,Alcohol,Binge drinking prevalence among adults aged >=...,16.9,%,Crude Prevalence,Overall,Overall
110,2016,US,United States,Alcohol,Binge drinking prevalence among adults aged >=...,21.9,%,Crude Prevalence,Gender,Male
220,2016,US,United States,Alcohol,Binge drinking prevalence among adults aged >=...,12,%,Crude Prevalence,Gender,Female
874,2016,US,United States,Alcohol,Binge drinking prevalence among women aged 18-...,18.7,%,Crude Prevalence,Overall,Overall
2943,2016,US,United States,Alcohol,Heavy drinking among adults aged >= 18 years,6.5,%,Crude Prevalence,Overall,Overall

In [19]:
# Separate CDI_US_crude into 3 stratification categories: Overall, Gender Male, Gender Female

# Overall
CDI_US_crude_overall = CDI_US_crude.loc[CDI_US_crude['Stratification1']=="Overall",:]
# Male
CDI_US_crude_male = CDI_US_crude.loc[CDI_US_crude['Stratification1']=="Male",:]
# Female
CDI_US_crude_female = CDI_US_crude.loc[CDI_US_crude['Stratification1']=="Female",:]

In [ ]:
CDI_US_crude_overall.head()

In [ ]:
CDI_US_crude_male.head()

In [ ]:
CDI_US_crude_female.head()

In [ ]:
# Only Age adjusted datavaluetypes
CDI_US_age_adjusted.head()

In [ ]:
# Separate CDI_US_crude into 3 stratification categories: Overall, Gender Male, Gender Female

# Overall
CDI_US_age_adjusted_overall = CDI_US_age_adjusted.loc[CDI_US_age_adjusted['Stratification1']=="Overall",:]
# Male
CDI_US_age_adjusted_male = CDI_US_age_adjusted.loc[CDI_US_age_adjusted['Stratification1']=="Male",:]
# Female
CDI_US_age_adjusted_female = CDI_US_age_adjusted.loc[CDI_US_age_adjusted['Stratification1']=="Female",:]

In [ ]:
CDI_US_age_adjusted_overall.head()

In [ ]:
CDI_US_age_adjusted_male.head()

In [ ]:
CDI_US_age_adjusted_female.head()