# ETL Project: Leading causes of death in the United States

#### Aim:
An analysis on the top 10 leading causes of death in the United States. This case study seeks to analyze the top causes of deaths from 2013 to 2016 by ranking death causes by year, state, and age-adjusted deaths. Further, would U.S. chronic disease indicators provide any insight into risk factors that may be associated with those leading causes of death? 

#### Notes:
* The 10 leading causes of death are classified by the International Classification of Diseases, Tenth Revision (ICD-10).
* Age-adjusted death rates are per 100,000 standard million population in the year 2000. 


#### Data sources:
* [CDC/HCHS](https://catalog.data.gov/dataset/age-adjusted-death-rates-for-the-top-10-leading-causes-of-death-united-states-2013)

* [CDC](https://catalog.data.gov/dataset/u-s-chronic-disease-indicators-cdi)

#### Tools:
* Jupter Notebook/Python 3
* MySQL

# Leading Causes Of Death In The United States
## Data Extraction And Transformation

After downloading csv files from our sources, csv files were extracted into dataframes utilizing jupyter notebook python 3 pandas function pd.read_csv().

In [1]:
# import dependencies
import pandas as pd
from sqlalchemy import create_engine

In [2]:
# read csv file for data on leading causes of death
leading_causes_death_df = pd.read_csv('Resources/NCHS_-_Leading_Causes_of_Death__United_States.csv')

In [3]:
# preview the dataframe created
leading_causes_death_df.head()

,Year,113 Cause Name,Cause Name,State,Deaths,Age-adjusted Death Rate
0,2016,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional injuries,Alabama,2755,55.5
1,2016,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional injuries,Alaska,439,63.1
2,2016,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional injuries,Arizona,4010,54.2
3,2016,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional injuries,Arkansas,1604,51.8
4,2016,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional injuries,California,13213,32.0

In our second source of data, Chronic Disease Indicators, which will be shown later, the categories of chronic disease our laid out into broad categories. Due to the specificity of the column '113 Cause Name' in the Leading Causes of Death data, it was decided that broader categories of death causes should be viewed to more closely match the Chronic Disease Indicators' categories for easier grouping of the two datasets. Thus utilizing the column 'Cause Name' as our main category. 

The column 'Age-adjusted Death Rate' was removed due to the lack of clarity from the datasource and not being able to to rank leading causes of death in a meaningful way.

In [4]:
## cleaning the dataframe

# Remove cause_name and state columns, Rename columns into a new dataframe
leading_causes = leading_causes_death_df[['Year', 'Cause Name', 'State','Deaths']].copy()
leading_causes = leading_causes.rename(columns={
    "Year":"year",
    "Cause Name": "cause_name",
    "State": "state",
    "Deaths": "deaths"
})
leading_causes.sort_values(by=["year"]).head()

       year              cause_name          state  deaths
10295  1999  Unintentional injuries        Wyoming     258
1418   1999     Alzheimer's disease      Minnesota    1083
8726   1999                 Suicide       Illinois    1020
7016   1999          Kidney disease       Michigan    1417
4334   1999                Diabetes  New Hampshire     294

In [5]:
# Filter leading_causes for years >=2013
leading_causes_2013_to_2016 = leading_causes.loc[leading_causes['year'] >= 2013,:]
leading_causes_2013_to_2016=leading_causes_2013_to_2016.sort_values(by=['year'])

#### PUT THIS DATAFRAME INTO THE DATABASE
leading_causes_2013_to_2016.head()

       year              cause_name          state  deaths
10281  2013  Unintentional injuries        Wyoming     325
3708   2013                    CLRD       Virginia    3181
3726   2013                    CLRD     Washington    2933
8946   2013                 Suicide        Montana     243
3744   2013                    CLRD  West Virginia    1590

In [6]:
# Remove all causes from dataframe
leading_causes_2013_to_2016_individual = leading_causes_2013_to_2016[leading_causes_2013_to_2016.cause_name != "All causes"]
leading_causes_2013_to_2016_individual.head()

       year              cause_name          state  deaths
10281  2013  Unintentional injuries        Wyoming     325
3708   2013                    CLRD       Virginia    3181
3726   2013                    CLRD     Washington    2933
8946   2013                 Suicide        Montana     243
3744   2013                    CLRD  West Virginia    1590

To determine the top 10 leading causes of death in the United States,

In [7]:
# Separate US from 2013 to 2016
leading_causes_2013_to_2016_individual_US = leading_causes_2013_to_2016_individual[leading_causes_2013_to_2016_individual.state == "United States"]
leading_causes_2013_to_2016_individual_US.head()

      year           cause_name          state  deaths
3654  2013                 CLRD  United States  149205
4590  2013             Diabetes  United States   75578
9270  2013              Suicide  United States   41149
1782  2013  Alzheimer's disease  United States   84767
2718  2013               Cancer  United States  584881

In [10]:
# ALL US 2013 Top 10 leading deaths
# Isolate only 2013 data
top_10_leading_2013_US = leading_causes_2013_to_2016_individual_US.loc[leading_causes_2013_to_2016_individual_US['year']==2013,:]
top_10_leading_2013_US = top_10_leading_2013_US.sort_values(by=['deaths'], ascending=False).head(10)
top_10_leading_2013_US

       year               cause_name          state  deaths
5528   2013            Heart disease  United States  611105
2718   2013                   Cancer  United States  584881
3654   2013                     CLRD  United States  149205
10162  2013   Unintentional injuries  United States  130557
8334   2013                   Stroke  United States  128978
1782   2013      Alzheimer's disease  United States   84767
4590   2013                 Diabetes  United States   75578
6462   2013  Influenza and pneumonia  United States   56979
7399   2013           Kidney disease  United States   47112
9270   2013                  Suicide  United States   41149

In [11]:
# ALL US 2014 Top 10 leading deaths
# Isolate only 2014 data
top_10_leading_2014_US = leading_causes_2013_to_2016_individual_US.loc[leading_causes_2013_to_2016_individual_US['year']==2014,:]
top_10_leading_2014_US = top_10_leading_2014_US.sort_values(by=['deaths'], ascending=False).head(10)
top_10_leading_2014_US

       year               cause_name          state  deaths
5527   2014            Heart disease  United States  614348
2717   2014                   Cancer  United States  591700
3653   2014                     CLRD  United States  147101
10161  2014   Unintentional injuries  United States  135928
8333   2014                   Stroke  United States  133103
1781   2014      Alzheimer's disease  United States   93541
4589   2014                 Diabetes  United States   76488
6461   2014  Influenza and pneumonia  United States   55227
7398   2014           Kidney disease  United States   48146
9269   2014                  Suicide  United States   42826

In [12]:
# ALL US 2015 Top 10 leading deaths
# Isolate only 2015 data
top_10_leading_2015_US = leading_causes_2013_to_2016_individual_US.loc[leading_causes_2013_to_2016_individual_US['year']==2015,:]
top_10_leading_2015_US = top_10_leading_2015_US.sort_values(by=['deaths'], ascending=False).head(10)
top_10_leading_2015_US

       year               cause_name          state  deaths
5526   2015            Heart disease  United States  633842
2716   2015                   Cancer  United States  595930
3652   2015                     CLRD  United States  155041
10160  2015   Unintentional injuries  United States  146571
8332   2015                   Stroke  United States  140323
1780   2015      Alzheimer's disease  United States  110561
4588   2015                 Diabetes  United States   79535
6460   2015  Influenza and pneumonia  United States   57062
7397   2015           Kidney disease  United States   49959
9268   2015                  Suicide  United States   44193

In [13]:
# ALL US 2016 Top 10 leading deaths
# Isolate only 2016 data
top_10_leading_2016_US = leading_causes_2013_to_2016_individual_US.loc[leading_causes_2013_to_2016_individual_US['year']==2016,:]
top_10_leading_2016_US = top_10_leading_2016_US.sort_values(by=['deaths'], ascending=False).head(10)
top_10_leading_2016_US

       year               cause_name          state  deaths
5525   2016            Heart disease  United States  635260
2715   2016                   Cancer  United States  598038
10159  2016   Unintentional injuries  United States  161374
3651   2016                     CLRD  United States  154596
8331   2016                   Stroke  United States  142142
1779   2016      Alzheimer's disease  United States  116103
4587   2016                 Diabetes  United States   80058
6459   2016  Influenza and pneumonia  United States   51537
7396   2016           Kidney disease  United States   50046
9267   2016                  Suicide  United States   44965

In [14]:
# Separate out states from 2013 to 2016
leading_causes_2013_to_2016_individual_states = leading_causes_2013_to_2016_individual[leading_causes_2013_to_2016_individual.state != "United States"]
leading_causes_2013_to_2016_individual_states.head()

       year              cause_name          state  deaths
10281  2013  Unintentional injuries        Wyoming     325
3708   2013                    CLRD       Virginia    3181
3726   2013                    CLRD     Washington    2933
8946   2013                 Suicide        Montana     243
3744   2013                    CLRD  West Virginia    1590

In [15]:
# ALL STATES 2013 Top 10 leading deaths
# Isolate only 2013 data
top_10_leading_2013_states = leading_causes_2013_to_2016_individual_states.loc[leading_causes_2013_to_2016_individual_states['year']==2013,:]
top_10_leading_2013_states = top_10_leading_2013_states.sort_values(by=['deaths'], ascending=False).head(10)
top_10_leading_2013_states

      year     cause_name         state  deaths
4806  2013  Heart disease    California   60299
1998  2013         Cancer    California   57714
5311  2013  Heart disease      New York   44039
2088  2013         Cancer       Florida   42735
4896  2013  Heart disease       Florida   42656
5510  2013  Heart disease         Texas   40203
2700  2013         Cancer         Texas   38412
2502  2013         Cancer      New York   35738
5419  2013  Heart disease  Pennsylvania   31629
2610  2013         Cancer  Pennsylvania   28512

In [16]:
# ALL STATES 2014 Top 10 leading deaths
# Isolate only 2014 data
top_10_leading_2014_states = leading_causes_2013_to_2016_individual_states.loc[leading_causes_2013_to_2016_individual_states['year']==2014,:]
top_10_leading_2014_states = top_10_leading_2014_states.sort_values(by=['deaths'], ascending=False).head(10)
top_10_leading_2014_states

      year     cause_name         state  deaths
1997  2014         Cancer    California   58412
4805  2014  Heart disease    California   58189
4895  2014  Heart disease       Florida   44511
2087  2014         Cancer       Florida   43212
5310  2014  Heart disease      New York   43116
5509  2014  Heart disease         Texas   41479
2699  2014         Cancer         Texas   38847
2501  2014         Cancer      New York   35392
5418  2014  Heart disease  Pennsylvania   31353
2609  2014         Cancer  Pennsylvania   28692

In [17]:
# ALL STATES 2015 Top 10 leading deaths
# Isolate only 2015 data
top_10_leading_2015_states = leading_causes_2013_to_2016_individual_states.loc[leading_causes_2013_to_2016_individual_states['year']==2015,:]
top_10_leading_2015_states = top_10_leading_2015_states.sort_values(by=['deaths'], ascending=False).head(10)
top_10_leading_2015_states

      year     cause_name         state  deaths
4804  2015  Heart disease    California   61289
1996  2015         Cancer    California   59629
4894  2015  Heart disease       Florida   45441
5309  2015  Heart disease      New York   44450
2086  2015         Cancer       Florida   44027
5508  2015  Heart disease         Texas   43298
2698  2015         Cancer         Texas   39121
2500  2015         Cancer      New York   35089
5417  2015  Heart disease  Pennsylvania   32042
2608  2015         Cancer  Pennsylvania   28697

In [18]:
# ALL STATES 2016 Top 10 leading deaths
# Isolate only 2016 data
top_10_leading_2016_states = leading_causes_2013_to_2016_individual_states.loc[leading_causes_2013_to_2016_individual_states['year']==2016,:]
top_10_leading_2016_states = top_10_leading_2016_states.sort_values(by=['deaths'], ascending=False).head(10)
top_10_leading_2016_states

      year     cause_name         state  deaths
4803  2016  Heart disease    California   61573
1995  2016         Cancer    California   59515
4893  2016  Heart disease       Florida   45659
2085  2016         Cancer       Florida   44266
5308  2016  Heart disease      New York   44076
5506  2016  Heart disease         Texas   43772
2697  2016         Cancer         Texas   40195
2499  2016         Cancer      New York   35368
5416  2016  Heart disease  Pennsylvania   31990
2607  2016         Cancer  Pennsylvania   28492

In [ ]:
# # Group dataframe by year and cause_name, finding the sum of deaths 
# leading_causes_2013_to_2016_grouped=leading_causes_2013_to_2016.groupby(["year", "cause_name"]).sum().copy()
# leading_causes_2013_to_2016_grouped.head()

# Chronic Disease Indicators

#### Column Descriptions:
* YearStart - Starting Year
* YearEnd - Ending Year
* LocationAbbr - Location Abbreviation
* LocationDesc - Location Description
* DataSource - Data Source Abbreviation
* Topic - Topic
* Question - Question full-length text
* Response - Response
* DataValueUnit - The unit, such as $, %, years, etc.
* DataValueType - The data type, such as prevalence or mean
* DataValue - Data Value, such as 14.7 or Category 1
* DataValueAlt - Equal to Data Value, but formatting is numeric
* DataValueFootnoteSymbol	- Footnote Symbol
* DatavalueFootnote - Footnote Text
* LowConfidenceLimit - Low Confidence Limit
* HighConfidenceLimit - High Confidence Limit
* StratificationCategory1	- The category of the stratification, such as * Gender, Overall, or Race/Ethnicity
* Stratification1	- The stratification within the category, such as Male or Female, White/non-Hispanic, Hispanic, Black/non-Hispanic, American Indian or Alaska Native, Asian or Pacific Islander, Multi-racial/non-Hispanic, Other/non-Hispanic, or Overall
* StratificationCategory2
* Stratification2	
* StratificationCategory3
* Stratification3	
* GeoLocation	- Location code to be used for Geocoding
* ResponseID - Identifier for the Response
* LocationID - Location Identifier
* TopicID	
* QuestionID - Question Identifier
* DataValueTypeID	- Identifier for the Data Value Type
* StratificationCategoryID1 - Identifier for stratification category 1
* StratificationID1 - Identifier for stratification 1
* StratificationCategoryID2	
* StratificationID2	
* StratificationCategoryID3	
* StratificationID3

In [24]:
# read chronic diseases indicators csv
CDI_df = pd.read_csv('Resources/U.S._Chronic_Disease_Indicators__CDI_.csv')
CDI_df.head()

C:\Users\ricem\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (7,10,18,19,20,21,23,30,31,32,33) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,YearStart,YearEnd,LocationAbbr,LocationDesc,DataSource,Topic,Question,Response,DataValueUnit,DataValueType,...,LocationID,TopicID,QuestionID,DataValueTypeID,StratificationCategoryID1,StratificationID1,StratificationCategoryID2,StratificationID2,StratificationCategoryID3,StratificationID3
0,2016,2016,US,United States,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,59,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
1,2016,2016,AL,Alabama,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,1,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
2,2016,2016,AK,Alaska,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,2,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
3,2016,2016,AZ,Arizona,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,4,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
4,2016,2016,AR,Arkansas,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,5,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN

In [25]:
## CLEAN UP DATAFRAME
# Select desired columns
CDI_df = CDI_df[['YearStart', 'LocationAbbr', 'LocationDesc', 'Topic', 'Question', 'DataValue', 'DataValueUnit', 'DataValueType', 'StratificationCategory1', 'Stratification1']]

CDI_df.head()

,YearStart,LocationAbbr,LocationDesc,Topic,Question,DataValue,DataValueUnit,DataValueType,StratificationCategory1,Stratification1
0,2016,US,United States,Alcohol,Binge drinking prevalence among adults aged >=...,16.9,%,Crude Prevalence,Overall,Overall
1,2016,AL,Alabama,Alcohol,Binge drinking prevalence among adults aged >=...,13,%,Crude Prevalence,Overall,Overall
2,2016,AK,Alaska,Alcohol,Binge drinking prevalence among adults aged >=...,18.2,%,Crude Prevalence,Overall,Overall
3,2016,AZ,Arizona,Alcohol,Binge drinking prevalence among adults aged >=...,15.6,%,Crude Prevalence,Overall,Overall
4,2016,AR,Arkansas,Alcohol,Binge drinking prevalence among adults aged >=...,15,%,Crude Prevalence,Overall,Overall

In [26]:
# Obtain rows only for the all of the United States
CDI_US = CDI_df.loc[CDI_df['LocationAbbr']=="US",:]

# Obtain rows only for the years >=2013
CDI_US = CDI_US.loc[CDI_US['YearStart']>=2013, :]
CDI_US

,YearStart,LocationAbbr,LocationDesc,Topic,Question,DataValue,DataValueUnit,DataValueType,StratificationCategory1,Stratification1
0,2016,US,United States,Alcohol,Binge drinking prevalence among adults aged >=...,16.9,%,Crude Prevalence,Overall,Overall
55,2016,US,United States,Alcohol,Binge drinking prevalence among adults aged >=...,17.9,%,Age-adjusted Prevalence,Overall,Overall
110,2016,US,United States,Alcohol,Binge drinking prevalence among adults aged >=...,21.9,%,Crude Prevalence,Gender,Male
165,2016,US,United States,Alcohol,Binge drinking prevalence among adults aged >=...,22.5,%,Age-adjusted Prevalence,Gender,Male
220,2016,US,United States,Alcohol,Binge drinking prevalence among adults aged >=...,12,%,Crude Prevalence,Gender,Female
275,2016,US,United States,Alcohol,Binge drinking prevalence among adults aged >=...,13.1,%,Age-adjusted Prevalence,Gender,Female
874,2016,US,United States,Alcohol,Binge drinking prevalence among women aged 18-...,18.7,%,Crude Prevalence,Overall,Overall
1201,2016,US,United States,Alcohol,Binge drinking frequency among adults aged >= ...,4.6,Number,Mean,Overall,Overall
1254,2016,US,United States,Alcohol,Binge drinking frequency among adults aged >= ...,4.7,Number,Age-adjusted Mean,Overall,Overall
1310,2016,US,United States,Alcohol,Binge drinking frequency among adults aged >= ...,5,Number,Mean,Gender,Male
1365,2016,US,United States,Alcohol,Binge drinking frequency among adults aged >= ...,5,Number,Age-adjusted Mean,Gender,Male
1420,2016,US,United States,Alcohol,Binge drinking frequency among adults aged >= ...,3.5,Number,Mean,Gender,Female
1475,2016,US,United States,Alcohol,Binge drinking frequency among adults aged >= ...,3.6,Number,Age-adjusted Mean,Gender,Female
1935,2016,US,United States,Alcohol,Binge drinking intensity among adults aged >= ...,7.4,Number,Mean,Overall,Overall
2125,2016,US,United States,Alcohol,Binge drinking intensity among adults aged >= ...,7.1,Number,Age-adjusted Mean,Overall,Overall
2180,2016,US,United States,Alcohol,Binge drinking intensity among adults aged >= ...,8.5,Number,Mean,Gender,Male
2235,2016,US,United States,Alcohol,Binge drinking intensity among adults aged >= ...,8.2,Number,Age-adjusted Mean,Gender,Male
2290,2016,US,United States,Alcohol,Binge drinking intensity among adults aged >= ...,5.6,Number,Mean,Gender,Female
2345,2016,US,United States,Alcohol,Binge drinking intensity among adults aged >= ...,5.3,Number,Age-adjusted Mean,Gender,Female
2943,2016,US,United States,Alcohol,Heavy drinking among adults aged >= 18 years,6.5,%,Crude Prevalence,Overall,Overall
2990,2016,US,United States,Alcohol,Heavy drinking among adults aged >= 18 years,6.7,%,Age-adjusted Prevalence,Overall,Overall
3045,2016,US,United States,Alcohol,Heavy drinking among adults aged >= 18 years,7.1,%,Crude Prevalence,Gender,Male
3100,2016,US,United States,Alcohol,Heavy drinking among adults aged >= 18 years,7.2,%,Age-adjusted Prevalence,Gender,Male
3155,2016,US,United States,Alcohol,Heavy drinking among adults aged >= 18 years,5.9,%,Crude Prevalence,Gender,Female
3210,2016,US,United States,Alcohol,Heavy drinking among adults aged >= 18 years,6,%,Age-adjusted Prevalence,Gender,Female
3806,2016,US,United States,Alcohol,Heavy drinking among women aged 18-44 years,6.6,%,Crude Prevalence,Overall,Overall
4134,2016,US,United States,Arthritis,Arthritis among adults aged >= 18 years,25.8,%,Crude Prevalence,Overall,Overall
4185,2016,US,United States,Arthritis,Arthritis among adults aged >= 18 years,23.9,%,Age-adjusted Prevalence,Overall,Overall
4240,2016,US,United States,Arthritis,Arthritis among adults aged >= 18 years,22.1,%,Crude Prevalence,Gender,Male
4295,2016,US,United States,Arthritis,Arthritis among adults aged >= 18 years,20.9,%,Age-adjusted Prevalence,Gender,Male
...,...,...,...,...,...,...,...,...,...,...
126316,2013,US,United States,Asthma,Asthma mortality rate,3630,NaN,Number,Overall,Overall
126417,2013,US,United States,Chronic Kidney Disease,Incidence of treated end-stage renal disease,326.3,"cases per 1,000,000","Adjusted by age, sex, race and ethnicity",Overall,Overall
126469,2013,US,United States,Chronic Kidney Disease,Incidence of treated end-stage renal disease,115877,"cases per 1,000,000",Number,Overall,Overall
126521,2013,US,United States,Chronic Kidney Disease,Incidence of treated end-stage renal disease a...,144.8,"cases per 1,000,000","Adjusted by age, sex, race and ethnicity",Overall,Overall
126573,2013,US,United States,Chronic Kidney Disease,Incidence of treated end-stage renal disease a...,51070,"cases per 1,000,000",Number,Overall,Overall
129745,2013,US,United States,Cardiovascular Disease,Cholesterol screening among adults aged >= 18 ...,80.4,%,Age-adjusted Prevalence,Gender,Female
129746,2013,US,United States,Cardiovascular Disease,Cholesterol screening among adults aged >= 18 ...,76.7,%,Age-adjusted Prevalence,Gender,Male
129747,2013,US,United States,Cardiovascular Disease,Cholesterol screening among adults aged >= 18 ...,78.5,%,Age-adjusted Prevalence,Overall,Overall
130183,2013,US,United States,Cardiovascular Disease,Cholesterol screening among adults aged >= 18 ...,82.2,%,Crude Prevalence,Gender,Female
130184,2013,US,United States,Cardiovascular Disease,Cholesterol screening among adults aged >= 18 ...,77.4,%,Crude Prevalence,Gender,Male
130185,2013,US,United States,Cardiovascular Disease,Cholesterol screening among adults aged >= 18 ...,80.1,%,Crude Prevalence,Overall,Overall
130622,2013,US,United States,Cardiovascular Disease,High cholesterol prevalence among adults aged ...,31.4,%,Age-adjusted Prevalence,Gender,Female
130623,2013,US,United States,Cardiovascular Disease,High cholesterol prevalence among adults aged ...,35.1,%,Age-adjusted Prevalence,Gender,Male
130624,2013,US,United States,Cardiovascular Disease,High cholesterol prevalence among adults aged ...,33.3,%,Age-adjusted Prevalence,Overall,Overall
131061,2013,US,United States,Cardiovascular Disease,High cholesterol prevalence among adults aged ...,38.4,%,Crude Prevalence,Overall,Overall
131062,2013,US,United States,Cardiovascular Disease,High cholesterol prevalence among adults aged ...,39.9,%,Crude Prevalence,Gender,Male
131063,2013,US,United States,Cardiovascular Disease,High cholesterol prevalence among adults aged ...,36.7,%,Crude Prevalence,Gender,Female
131787,2013,US,United States,Overarching Conditions,Gini Index of income inequality,0.47,NaN,Number,Overall,Overall
132703,2013,US,United States,"Nutrition, Physical Activity, and Weight Status",Median daily frequency of fruit consumption am...,1.1,Number,Median,Gender,Female
132704,2013,US,United States,"Nutrition, Physical Activity, and Weight Status",Median daily frequency of fruit consumption am...,1,Number,Median,Gender,Male
132705,2013,US,United States,"Nutrition, Physical Activity, and Weight Status",Median daily frequency of fruit consumption am...,1,Number,Median,Overall,Overall
133141,2013,US,United States,"Nutrition, Physical Activity, and Weight Status",Median daily frequency of vegetable consumptio...,1.4,Number,Median,Gender,Female
133142,2013,US,United States,"Nutrition, Physical Activity, and Weight Status",Median daily frequency of vegetable consumptio...,1.3,Number,Median,Gender,Male
133143,2013,US,United States,"Nutrition, Physical Activity, and Weight Status",Median daily frequency of vegetable consumptio...,1.3,Number,Median,Overall,Overall
133583,2013,US,United States,Tobacco,Quit attempts in the past year among current s...,66.5,%,Age-adjusted Prevalence,Gender,Female
133584,2013,US,United States,Tobacco,Quit attempts in the past year among current s...,64.4,%,Age-adjusted Prevalence,Gender,Male
133585,2013,US,United States,Tobacco,Quit attempts in the past year among current s...,65.4,%,Age-adjusted Prevalence,Overall,Overall
134017,2013,US,United States,Tobacco,Quit attempts in the past year among current s...,66.8,%,Crude Prevalence,Gender,Female
134018,2013,US,United States,Tobacco,Quit attempts in the past year among current s...,65,%,Crude Prevalence,Gender,Male
134019,2013,US,United States,Tobacco,Quit attempts in the past year among current s...,65.9,%,Crude Prevalence,Overall,Overall

In [27]:
# Separate crude prevalence and age-adjusted prevalence into separate dataframes
CDI_US_crude = CDI_US.loc[CDI_US['DataValueType']=="Crude Prevalence",:]
CDI_US_age_adjusted = CDI_US.loc[CDI_US['DataValueType']=="Age-adjusted Prevalence", :]

## Chronic Disease Indicator Analysis In The US

In [28]:
CDI_US_crude.head()

,YearStart,LocationAbbr,LocationDesc,Topic,Question,DataValue,DataValueUnit,DataValueType,StratificationCategory1,Stratification1
0,2016,US,United States,Alcohol,Binge drinking prevalence among adults aged >=...,16.9,%,Crude Prevalence,Overall,Overall
110,2016,US,United States,Alcohol,Binge drinking prevalence among adults aged >=...,21.9,%,Crude Prevalence,Gender,Male
220,2016,US,United States,Alcohol,Binge drinking prevalence among adults aged >=...,12,%,Crude Prevalence,Gender,Female
874,2016,US,United States,Alcohol,Binge drinking prevalence among women aged 18-...,18.7,%,Crude Prevalence,Overall,Overall
2943,2016,US,United States,Alcohol,Heavy drinking among adults aged >= 18 years,6.5,%,Crude Prevalence,Overall,Overall

In [29]:
# Separate CDI_US_crude into 3 stratification categories: Overall, Gender Male, Gender Female

# Overall
CDI_US_crude_overall = CDI_US_crude.loc[CDI_US_crude['Stratification1']=="Overall",:]
# Male
CDI_US_crude_male = CDI_US_crude.loc[CDI_US_crude['Stratification1']=="Male",:]
# Female
CDI_US_crude_female = CDI_US_crude.loc[CDI_US_crude['Stratification1']=="Female",:]

In [30]:
CDI_US_crude_overall.head()

,YearStart,LocationAbbr,LocationDesc,Topic,Question,DataValue,DataValueUnit,DataValueType,StratificationCategory1,Stratification1
0,2016,US,United States,Alcohol,Binge drinking prevalence among adults aged >=...,16.9,%,Crude Prevalence,Overall,Overall
874,2016,US,United States,Alcohol,Binge drinking prevalence among women aged 18-...,18.7,%,Crude Prevalence,Overall,Overall
2943,2016,US,United States,Alcohol,Heavy drinking among adults aged >= 18 years,6.5,%,Crude Prevalence,Overall,Overall
3806,2016,US,United States,Alcohol,Heavy drinking among women aged 18-44 years,6.6,%,Crude Prevalence,Overall,Overall
4134,2016,US,United States,Arthritis,Arthritis among adults aged >= 18 years,25.8,%,Crude Prevalence,Overall,Overall

In [31]:
CDI_US_crude_male.head()

,YearStart,LocationAbbr,LocationDesc,Topic,Question,DataValue,DataValueUnit,DataValueType,StratificationCategory1,Stratification1
110,2016,US,United States,Alcohol,Binge drinking prevalence among adults aged >=...,21.9,%,Crude Prevalence,Gender,Male
3045,2016,US,United States,Alcohol,Heavy drinking among adults aged >= 18 years,7.1,%,Crude Prevalence,Gender,Male
4240,2016,US,United States,Arthritis,Arthritis among adults aged >= 18 years,22.1,%,Crude Prevalence,Gender,Male
5111,2016,US,United States,Arthritis,Arthritis among adults aged >= 18 years who ar...,30.6,%,Crude Prevalence,Gender,Male
5983,2016,US,United States,Arthritis,Arthritis among adults aged >= 18 years who ha...,47.3,%,Crude Prevalence,Gender,Male

In [32]:
CDI_US_crude_female.head()

,YearStart,LocationAbbr,LocationDesc,Topic,Question,DataValue,DataValueUnit,DataValueType,StratificationCategory1,Stratification1
220,2016,US,United States,Alcohol,Binge drinking prevalence among adults aged >=...,12,%,Crude Prevalence,Gender,Female
3155,2016,US,United States,Alcohol,Heavy drinking among adults aged >= 18 years,5.9,%,Crude Prevalence,Gender,Female
4350,2016,US,United States,Arthritis,Arthritis among adults aged >= 18 years,29,%,Crude Prevalence,Gender,Female
5221,2016,US,United States,Arthritis,Arthritis among adults aged >= 18 years who ar...,39.6,%,Crude Prevalence,Gender,Female
6093,2016,US,United States,Arthritis,Arthritis among adults aged >= 18 years who ha...,57.1,%,Crude Prevalence,Gender,Female

In [33]:
# Only Age adjusted datavaluetypes
CDI_US_age_adjusted.head()

,YearStart,LocationAbbr,LocationDesc,Topic,Question,DataValue,DataValueUnit,DataValueType,StratificationCategory1,Stratification1
55,2016,US,United States,Alcohol,Binge drinking prevalence among adults aged >=...,17.9,%,Age-adjusted Prevalence,Overall,Overall
165,2016,US,United States,Alcohol,Binge drinking prevalence among adults aged >=...,22.5,%,Age-adjusted Prevalence,Gender,Male
275,2016,US,United States,Alcohol,Binge drinking prevalence among adults aged >=...,13.1,%,Age-adjusted Prevalence,Gender,Female
2990,2016,US,United States,Alcohol,Heavy drinking among adults aged >= 18 years,6.7,%,Age-adjusted Prevalence,Overall,Overall
3100,2016,US,United States,Alcohol,Heavy drinking among adults aged >= 18 years,7.2,%,Age-adjusted Prevalence,Gender,Male

In [34]:
# Separate CDI_US_age_adjusted into 3 stratification categories: Overall, Gender Male, Gender Female

# Overall
CDI_US_age_adjusted_overall = CDI_US_age_adjusted.loc[CDI_US_age_adjusted['Stratification1']=="Overall",:]
# Male
CDI_US_age_adjusted_male = CDI_US_age_adjusted.loc[CDI_US_age_adjusted['Stratification1']=="Male",:]
# Female
CDI_US_age_adjusted_female = CDI_US_age_adjusted.loc[CDI_US_age_adjusted['Stratification1']=="Female",:]

In [35]:
CDI_US_age_adjusted_overall.head()

,YearStart,LocationAbbr,LocationDesc,Topic,Question,DataValue,DataValueUnit,DataValueType,StratificationCategory1,Stratification1
55,2016,US,United States,Alcohol,Binge drinking prevalence among adults aged >=...,17.9,%,Age-adjusted Prevalence,Overall,Overall
2990,2016,US,United States,Alcohol,Heavy drinking among adults aged >= 18 years,6.7,%,Age-adjusted Prevalence,Overall,Overall
4185,2016,US,United States,Arthritis,Arthritis among adults aged >= 18 years,23.9,%,Age-adjusted Prevalence,Overall,Overall
5056,2016,US,United States,Arthritis,Arthritis among adults aged >= 18 years who ar...,30.8,%,Age-adjusted Prevalence,Overall,Overall
5928,2016,US,United States,Arthritis,Arthritis among adults aged >= 18 years who ha...,37.6,%,Age-adjusted Prevalence,Overall,Overall

In [36]:
CDI_US_age_adjusted_male.head()

,YearStart,LocationAbbr,LocationDesc,Topic,Question,DataValue,DataValueUnit,DataValueType,StratificationCategory1,Stratification1
165,2016,US,United States,Alcohol,Binge drinking prevalence among adults aged >=...,22.5,%,Age-adjusted Prevalence,Gender,Male
3100,2016,US,United States,Alcohol,Heavy drinking among adults aged >= 18 years,7.2,%,Age-adjusted Prevalence,Gender,Male
4295,2016,US,United States,Arthritis,Arthritis among adults aged >= 18 years,20.9,%,Age-adjusted Prevalence,Gender,Male
5166,2016,US,United States,Arthritis,Arthritis among adults aged >= 18 years who ar...,27.2,%,Age-adjusted Prevalence,Gender,Male
6038,2016,US,United States,Arthritis,Arthritis among adults aged >= 18 years who ha...,33,%,Age-adjusted Prevalence,Gender,Male

In [37]:
CDI_US_age_adjusted_female.head()

,YearStart,LocationAbbr,LocationDesc,Topic,Question,DataValue,DataValueUnit,DataValueType,StratificationCategory1,Stratification1
275,2016,US,United States,Alcohol,Binge drinking prevalence among adults aged >=...,13.1,%,Age-adjusted Prevalence,Gender,Female
3210,2016,US,United States,Alcohol,Heavy drinking among adults aged >= 18 years,6,%,Age-adjusted Prevalence,Gender,Female
4405,2016,US,United States,Arthritis,Arthritis among adults aged >= 18 years,26.1,%,Age-adjusted Prevalence,Gender,Female
5276,2016,US,United States,Arthritis,Arthritis among adults aged >= 18 years who ar...,34.8,%,Age-adjusted Prevalence,Gender,Female
6148,2016,US,United States,Arthritis,Arthritis among adults aged >= 18 years who ha...,41.3,%,Age-adjusted Prevalence,Gender,Female

## Chronic Disease Indicators Analysis By State

In [47]:
# Obtain rows only for the all states
CDI_states = CDI_df.loc[CDI_df['LocationAbbr'] !="US",:]

# Obtain rows only for the years >=2013
CDI_states = CDI_states.loc[CDI_states['YearStart'] >=2013,:]
CDI_states

,YearStart,LocationAbbr,LocationDesc,Topic,Question,DataValue,DataValueUnit,DataValueType,StratificationCategory1,Stratification1
1,2016,AL,Alabama,Alcohol,Binge drinking prevalence among adults aged >=...,13,%,Crude Prevalence,Overall,Overall
2,2016,AK,Alaska,Alcohol,Binge drinking prevalence among adults aged >=...,18.2,%,Crude Prevalence,Overall,Overall
3,2016,AZ,Arizona,Alcohol,Binge drinking prevalence among adults aged >=...,15.6,%,Crude Prevalence,Overall,Overall
4,2016,AR,Arkansas,Alcohol,Binge drinking prevalence among adults aged >=...,15,%,Crude Prevalence,Overall,Overall
5,2016,CA,California,Alcohol,Binge drinking prevalence among adults aged >=...,16.3,%,Crude Prevalence,Overall,Overall
6,2016,CO,Colorado,Alcohol,Binge drinking prevalence among adults aged >=...,19,%,Crude Prevalence,Overall,Overall
7,2016,CT,Connecticut,Alcohol,Binge drinking prevalence among adults aged >=...,16.7,%,Crude Prevalence,Overall,Overall
8,2016,DE,Delaware,Alcohol,Binge drinking prevalence among adults aged >=...,17,%,Crude Prevalence,Overall,Overall
9,2016,DC,District of Columbia,Alcohol,Binge drinking prevalence among adults aged >=...,25.6,%,Crude Prevalence,Overall,Overall
10,2016,FL,Florida,Alcohol,Binge drinking prevalence among adults aged >=...,15.5,%,Crude Prevalence,Overall,Overall
11,2016,GA,Georgia,Alcohol,Binge drinking prevalence among adults aged >=...,13.3,%,Crude Prevalence,Overall,Overall
12,2016,HI,Hawaii,Alcohol,Binge drinking prevalence among adults aged >=...,18.6,%,Crude Prevalence,Overall,Overall
13,2016,ID,Idaho,Alcohol,Binge drinking prevalence among adults aged >=...,16.1,%,Crude Prevalence,Overall,Overall
14,2016,IL,Illinois,Alcohol,Binge drinking prevalence among adults aged >=...,19.9,%,Crude Prevalence,Overall,Overall
15,2016,IN,Indiana,Alcohol,Binge drinking prevalence among adults aged >=...,17.5,%,Crude Prevalence,Overall,Overall
16,2016,IA,Iowa,Alcohol,Binge drinking prevalence among adults aged >=...,21.2,%,Crude Prevalence,Overall,Overall
17,2016,KS,Kansas,Alcohol,Binge drinking prevalence among adults aged >=...,16,%,Crude Prevalence,Overall,Overall
18,2016,KY,Kentucky,Alcohol,Binge drinking prevalence among adults aged >=...,14.6,%,Crude Prevalence,Overall,Overall
19,2016,LA,Louisiana,Alcohol,Binge drinking prevalence among adults aged >=...,16.9,%,Crude Prevalence,Overall,Overall
20,2016,ME,Maine,Alcohol,Binge drinking prevalence among adults aged >=...,18.3,%,Crude Prevalence,Overall,Overall
21,2016,MD,Maryland,Alcohol,Binge drinking prevalence among adults aged >=...,15.3,%,Crude Prevalence,Overall,Overall
22,2016,MA,Massachusetts,Alcohol,Binge drinking prevalence among adults aged >=...,17.8,%,Crude Prevalence,Overall,Overall
23,2016,MI,Michigan,Alcohol,Binge drinking prevalence among adults aged >=...,19,%,Crude Prevalence,Overall,Overall
24,2016,MN,Minnesota,Alcohol,Binge drinking prevalence among adults aged >=...,21.3,%,Crude Prevalence,Overall,Overall
25,2016,MS,Mississippi,Alcohol,Binge drinking prevalence among adults aged >=...,12.3,%,Crude Prevalence,Overall,Overall
26,2016,MO,Missouri,Alcohol,Binge drinking prevalence among adults aged >=...,18.4,%,Crude Prevalence,Overall,Overall
27,2016,MT,Montana,Alcohol,Binge drinking prevalence among adults aged >=...,18.9,%,Crude Prevalence,Overall,Overall
28,2016,NE,Nebraska,Alcohol,Binge drinking prevalence among adults aged >=...,20,%,Crude Prevalence,Overall,Overall
29,2016,NV,Nevada,Alcohol,Binge drinking prevalence among adults aged >=...,15.8,%,Crude Prevalence,Overall,Overall
30,2016,NH,New Hampshire,Alcohol,Binge drinking prevalence among adults aged >=...,18,%,Crude Prevalence,Overall,Overall
...,...,...,...,...,...,...,...,...,...,...
134053,2013,WA,Washington,Tobacco,Quit attempts in the past year among current s...,70.2,%,Crude Prevalence,Race/Ethnicity,Hispanic
134054,2013,WA,Washington,Tobacco,Quit attempts in the past year among current s...,67.6,%,Crude Prevalence,Gender,Male
134055,2013,WA,Washington,Tobacco,Quit attempts in the past year among current s...,54.5,%,Crude Prevalence,Race/Ethnicity,"Multiracial, non-Hispanic"
134056,2013,WA,Washington,Tobacco,Quit attempts in the past year among current s...,63.3,%,Crude Prevalence,Race/Ethnicity,"Other, non-Hispanic"
134057,2013,WA,Washington,Tobacco,Quit attempts in the past year among current s...,67.5,%,Crude Prevalence,Overall,Overall
134058,2013,WA,Washington,Tobacco,Quit attempts in the past year among current s...,67.5,%,Crude Prevalence,Race/Ethnicity,"White, non-Hispanic"
134059,2013,WI,Wisconsin,Tobacco,Quit attempts in the past year among current s...,85.1,%,Crude Prevalence,Race/Ethnicity,"Black, non-Hispanic"
134060,2013,WI,Wisconsin,Tobacco,Quit attempts in the past year among current s...,74.7,%,Crude Prevalence,Gender,Female
134061,2013,WI,Wisconsin,Tobacco,Quit attempts in the past year among current s...,NaN,%,Crude Prevalence,Race/Ethnicity,Hispanic
134062,2013,WI,Wisconsin,Tobacco,Quit attempts in the past year among current s...,68.5,%,Crude Prevalence,Gender,Male
134063,2013,WI,Wisconsin,Tobacco,Quit attempts in the past year among current s...,NaN,%,Crude Prevalence,Race/Ethnicity,"Multiracial, non-Hispanic"
134064,2013,WI,Wisconsin,Tobacco,Quit attempts in the past year among current s...,62.5,%,Crude Prevalence,Race/Ethnicity,"Other, non-Hispanic"
134065,2013,WI,Wisconsin,Tobacco,Quit attempts in the past year among current s...,71.3,%,Crude Prevalence,Overall,Overall
134066,2013,WI,Wisconsin,Tobacco,Quit attempts in the past year among current s...,70.3,%,Crude Prevalence,Race/Ethnicity,"White, non-Hispanic"
134067,2013,WV,West Virginia,Tobacco,Quit attempts in the past year among current s...,NaN,%,Crude Prevalence,Race/Ethnicity,"Black, non-Hispanic"
134068,2013,WV,West Virginia,Tobacco,Quit attempts in the past year among current s...,58.9,%,Crude Prevalence,Gender,Female
134069,2013,WV,West Virginia,Tobacco,Quit attempts in the past year among current s...,NaN,%,Crude Prevalence,Race/Ethnicity,Hispanic
134070,2013,WV,West Virginia,Tobacco,Quit attempts in the past year among current s...,60.5,%,Crude Prevalence,Gender,Male
134071,2013,WV,West Virginia,Tobacco,Quit attempts in the past year among current s...,77.9,%,Crude Prevalence,Race/Ethnicity,"Multiracial, non-Hispanic"
134072,2013,WV,West Virginia,Tobacco,Quit attempts in the past year among current s...,NaN,%,Crude Prevalence,Race/Ethnicity,"Other, non-Hispanic"
134073,2013,WV,West Virginia,Tobacco,Quit attempts in the past year among current s...,59.7,%,Crude Prevalence,Overall,Overall
134074,2013,WV,West Virginia,Tobacco,Quit attempts in the past year among current s...,59.3,%,Crude Prevalence,Race/Ethnicity,"White, non-Hispanic"
134075,2013,WY,Wyoming,Tobacco,Quit attempts in the past year among current s...,NaN,%,Crude Prevalence,Race/Ethnicity,"Black, non-Hispanic"
134076,2013,WY,Wyoming,Tobacco,Quit attempts in the past year among current s...,66.9,%,Crude Prevalence,Gender,Female
134077,2013,WY,Wyoming,Tobacco,Quit attempts in the past year among current s...,71.1,%,Crude Prevalence,Race/Ethnicity,Hispanic
134078,2013,WY,Wyoming,Tobacco,Quit attempts in the past year among current s...,59.3,%,Crude Prevalence,Gender,Male
134079,2013,WY,Wyoming,Tobacco,Quit attempts in the past year among current s...,NaN,%,Crude Prevalence,Race/Ethnicity,"Multiracial, non-Hispanic"
134080,2013,WY,Wyoming,Tobacco,Quit attempts in the past year among current s...,NaN,%,Crude Prevalence,Race/Ethnicity,"Other, non-Hispanic"
134081,2013,WY,Wyoming,Tobacco,Quit attempts in the past year among current s...,62.7,%,Crude Prevalence,Overall,Overall
134082,2013,WY,Wyoming,Tobacco,Quit attempts in the past year among current s...,60.6,%,Crude Prevalence,Race/Ethnicity,"White, non-Hispanic"

In [52]:
# Separate crude prevalence and age-adjusted prevalence into separate dataframes
CDI_states_crude = CDI_states.loc[CDI_states['DataValueType']=="Crude Prevalence",:]
CDI_states_age_adjusted = CDI_states.loc[CDI_states['DataValueType']=="Age-adjusted Prevalence", :]

,YearStart,LocationAbbr,LocationDesc,Topic,Question,DataValue,DataValueUnit,DataValueType,StratificationCategory1,Stratification1
1,2016,AL,Alabama,Alcohol,Binge drinking prevalence among adults aged >=...,13,%,Crude Prevalence,Overall,Overall
2,2016,AK,Alaska,Alcohol,Binge drinking prevalence among adults aged >=...,18.2,%,Crude Prevalence,Overall,Overall
3,2016,AZ,Arizona,Alcohol,Binge drinking prevalence among adults aged >=...,15.6,%,Crude Prevalence,Overall,Overall
4,2016,AR,Arkansas,Alcohol,Binge drinking prevalence among adults aged >=...,15,%,Crude Prevalence,Overall,Overall
5,2016,CA,California,Alcohol,Binge drinking prevalence among adults aged >=...,16.3,%,Crude Prevalence,Overall,Overall

In [53]:
# Separate CDI_states_crude into 3 stratification categories: Overall, Gender Male, Gender Female

# Overall
CDI_states_crude_overall = CDI_states_crude.loc[CDI_states_crude['Stratification1']=="Overall",:]
# Male
CDI_states_crude_male = CDI_states_crude.loc[CDI_states_crude['Stratification1']=="Male",:]
# Female
CDI_states_crude_female = CDI_states_crude.loc[CDI_states_crude['Stratification1']=="Female",:]

In [70]:
## Separate CDI_states_crude_{overall, male, female} by year

# CDI state crude overall (sco)
CDI_sco_2013 = CDI_states_crude_overall.loc[CDI_states_crude_overall['YearStart']==2013,:]
CDI_sco_2014 = CDI_states_crude_overall.loc[CDI_states_crude_overall['YearStart']==2014,:]
CDI_sco_2015 = CDI_states_crude_overall.loc[CDI_states_crude_overall['YearStart']==2015,:]
CDI_sco_2016 = CDI_states_crude_overall.loc[CDI_states_crude_overall['YearStart']==2016,:]

# CDI state crude male (scm)
CDI_scm_2013 = CDI_states_crude_male.loc[CDI_states_crude_male['YearStart']==2013,:]
CDI_scm_2014 = CDI_states_crude_male.loc[CDI_states_crude_male['YearStart']==2014,:]
CDI_scm_2015 = CDI_states_crude_male.loc[CDI_states_crude_male['YearStart']==2015,:]
CDI_scm_2016 = CDI_states_crude_male.loc[CDI_states_crude_male['YearStart']==2016,:]

# CDI state crude female (scf)
CDI_scf_2013 = CDI_states_crude_female.loc[CDI_states_crude_female['YearStart']==2013,:]
CDI_scf_2014 = CDI_states_crude_female.loc[CDI_states_crude_female['YearStart']==2014,:]
CDI_scf_2015 = CDI_states_crude_female.loc[CDI_states_crude_female['YearStart']==2015,:]
CDI_scf_2016 = CDI_states_crude_female.loc[CDI_states_crude_female['YearStart']==2016,:]

In [71]:
# Separate CDI_states_age_adjusted into 3 stratification categories: Overall, Gender Male, Gender Female

# Overall
CDI_states_age_adjusted_overall = CDI_states_age_adjusted.loc[CDI_states_age_adjusted['Stratification1']=="Overall",:]
# Male
CDI_states_age_adjusted_male = CDI_states_age_adjusted.loc[CDI_states_age_adjusted['Stratification1']=="Male",:]
# Female
CDI_states_age_adjusted_female = CDI_states_age_adjusted.loc[CDI_states_age_adjusted['Stratification1']=="Female",:]

In [72]:
## Separate CDI_states_age_adjusted_{overall, male, female} by year

# CDI state crude overall (sco)
CDI_sao_2013 = CDI_states_age_adjusted_overall.loc[CDI_states_age_adjusted_overall['YearStart']==2013,:]
CDI_sao_2014 = CDI_states_age_adjusted_overall.loc[CDI_states_age_adjusted_overall['YearStart']==2014,:]
CDI_sao_2015 = CDI_states_age_adjusted_overall.loc[CDI_states_age_adjusted_overall['YearStart']==2015,:]
CDI_sao_2016 = CDI_states_age_adjusted_overall.loc[CDI_states_age_adjusted_overall['YearStart']==2016,:]

# CDI state crude male (scm)
CDI_sam_2013 = CDI_states_age_adjusted_male.loc[CDI_states_age_adjusted_male['YearStart']==2013,:]
CDI_sam_2014 = CDI_states_age_adjusted_male.loc[CDI_states_age_adjusted_male['YearStart']==2014,:]
CDI_sam_2015 = CDI_states_age_adjusted_male.loc[CDI_states_age_adjusted_male['YearStart']==2015,:]
CDI_sam_2016 = CDI_states_age_adjusted_male.loc[CDI_states_age_adjusted_male['YearStart']==2016,:]

# CDI state crude female (scf)
CDI_saf_2013 = CDI_states_age_adjusted_female.loc[CDI_states_age_adjusted_female['YearStart']==2013,:]
CDI_saf_2014 = CDI_states_age_adjusted_female.loc[CDI_states_age_adjusted_female['YearStart']==2014,:]
CDI_saf_2015 = CDI_states_age_adjusted_female.loc[CDI_states_age_adjusted_female['YearStart']==2015,:]
CDI_saf_2016 = CDI_states_age_adjusted_female.loc[CDI_states_age_adjusted_female['YearStart']==2016,:]

## Connect to MySQL database

In [73]:
engine = create_engine("mysql://root:Codingislife92!@localhost:3306/leading_causes_of_death_db")

In [74]:
leading_causes_2013_to_2016.to_sql(name='leading_causes', con=engine, if_exists='append', index=False)
pd.read_sql_query('SELECT * FROM leading_causes', con=engine).head()

,year,cause_name,state,deaths,age-ajusted_death_rate
0,2013,"Accidents (unintentional injuries) (V01-X59,Y8...",Wyoming,325,55.2
1,2013,Chronic lower respiratory diseases (J40-J47),Virginia,3181,37.3
2,2013,Chronic lower respiratory diseases (J40-J47),Washington,2933,39.4
3,2013,"Intentional self-harm (suicide) (*U03,X60-X84,...",Montana,243,23.7
4,2013,Chronic lower respiratory diseases (J40-J47),West Virginia,1590,64.6

In [75]:
# QUERY TO SUM DEATHS, GROUPED BY YEAR AND CAUSE OF DEATH

pd.read_sql_query('SELECT year, state,\
                  SUM(deaths) as total_US_deaths\
                  FROM leading_causes\
                  GROUP BY year, cause_name\
                  HAVING year >= 2013\
                  ORDER BY year ASC', con=engine)

    year                 state  total_US_deaths
0   2013               Wyoming         261114.0
1   2013            California       25969930.0
2   2013         United States         678136.0
3   2013         United States         169534.0
4   2013              Illinois        4679048.0
5   2013                  Ohio         257956.0
6   2013              Virginia         298410.0
7   2013              Virginia        1193640.0
8   2013               Alabama         604624.0
9   2013               Alabama         151156.0
10  2013               Alabama        1222210.0
11  2013               Alabama        4888840.0
12  2013             Tennessee         455832.0
13  2013             Tennessee         113958.0
14  2013               Montana          82298.0
15  2013                Hawaii         376896.0
16  2013              Illinois        1169762.0
17  2013                Hawaii          94224.0
18  2013                  Ohio        1031824.0
19  2013               Montana         329192.0
20  2013               Wyoming        1044456.0
21  2014                  Iowa         271856.0
22  2014            Washington       26264180.0
23  2014              Delaware         748328.0
24  2014              Delaware         187082.0
25  2014             Wisconsin        4733600.0
26  2014        South Carolina         266206.0
27  2014             Wisconsin         294202.0
28  2014             Wisconsin        1176808.0
29  2014               Arizona         611904.0
..   ...                   ...              ...
54  2015               Georgia         456496.0
55  2015               Georgia         114124.0
56  2015               Montana          88386.0
57  2015              Kentucky         399672.0
58  2015               Indiana        1191860.0
59  2015              Kentucky          99918.0
60  2015              Colorado        1122584.0
61  2015               Montana         353544.0
62  2015               Wyoming        1172568.0
63  2016         United States         322748.0
64  2016               Alabama       25318615.0
65  2016               Wyoming         928824.0
66  2016               Wyoming         232206.0
67  2016               Alabama        4784304.0
68  2016             Minnesota         284284.0
69  2016  District of Columbia         309192.0
70  2016  District of Columbia        1236768.0
71  2016              Kentucky         640464.0
72  2016              Kentucky         160116.0
73  2016              Nebraska        1270520.0
74  2016              Nebraska        5082080.0
75  2016                Oregon         412296.0
76  2016                Oregon         103074.0
77  2016             Wisconsin          89930.0
78  2016               Alabama         400368.0
79  2016               Alabama        1196076.0
80  2016               Alabama         100092.0
81  2016             Minnesota        1137136.0
82  2016             Wisconsin         359720.0
83  2016         United States        1290992.0

[84 rows x 3 columns]